title: "Takuma Yoneda"
author: "Takuma Yoneda"
description: "PhD candidate at TTIC, interested in Deep RL, robotics and NLP."
lang: "en"
markdown: kramdown

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
hide_title: false            # remove site heading in the header
hide_footer: false           # hide the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  # - index.html
  # - README.md
#  - title: "https://"       # linking external sites is also supported

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  newspaper: "/archive"
  envelope: "mailto:takuma@ttic.edu"
  github: "https://github.com/takuma-yoneda"
  twitter: "https://twitter.com/takuma_yoneda"
  # rss: "/contrast/feed.xml"
  # user: "/"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

google_analytics: UA-101863959-2

plugins: 
 - jekyll-feed
 - jekyll-default-layout
 - jekyll-redirect-from
